#name: Python CI
#
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
#
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#
#    steps:
#      # step 1 : checkout the code from the repository
#      - name: Check out code
#        uses: actions/checkout@v2
#
#      # step 2 : Set up python environment
#      - name: Set up Python
#        uses: actions/setup-python@v2
#        with:
#          python-version: '3.11'
#
#      # step 3 : Install dependencies
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#
#      # step 4 : Run tests
#      - name: Run tests
#        run: pytest
#

name: Python CI with CML Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and save report
        run: |
          pytest --tb=short > result.txt

      - name: CML comment with report
        env:
          REPO_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cat result.txt
          echo "## 🧪 Test Report (Sanity Check)" > report.md
          echo "\`\`\`" >> report.md
          cat result.txt >> report.md
          echo "\`\`\`" >> report.md
          cml comment create report.md
